networks:
    luizalabs:
        driver: bridge

volumes:
  luiza_data_db:
  luiza_data_test:

services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.entrypoints.app:create_app
      - FLASK_ENV=development
    env_file:
      - .env
    depends_on:
      - db
      - cache
    networks:
      - luizalabs

  db:
    image: postgres:16.3
    container_name: luiza_db
    environment:
      POSTGRES_USER: luizalabs
      POSTGRES_PASSWORD: luizalabs123
      POSTGRES_DB: luizalabsdb
    volumes:
      - luiza_data_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - luizalabs

  db-test:
    image: postgres:16.3
    container_name: luiza_db_test
    environment:
      POSTGRES_USER: luizalabs
      POSTGRES_PASSWORD: luizalabs123
      POSTGRES_DB: luizalabsdb
    volumes:
      - luiza_data_test:/var/lib/postgresql/data
    networks:
      - luizalabs

  cache:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - luizalabs